version: "3.3"

services:
    client:
        build:
            context: ./client
            dockerfile: ./builder/Dockerfile.production
        command: nginx -g "daemon off;"
    server:
        build:
            context: ./server
            dockerfile: ./builder/Dockerfile.production
        command: pm2-runtime npm -- start
