version: "3.3"
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.production
        command: nginx -g "daemon off;"
        ports:
            - 10000:80
        environment:
            - NODE_ENV=production
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.production
        command: pm2-runtime npm -- start
        environment:
            - NODE_ENV=production
