version: "3.7"
services:
    client:
        image: node:12.8.1-alpine
        working_dir: /app
        command: npm start
        volumes:
            - ./client:/app
            - /app/node_modules
        networks:
            - geek-regime
        ports:
            - 10000:3000
        depends_on:
            - server
            - postgres
            - redis
    server:
        image: node:12.8.1-alpine
        working_dir: /app
        command: npm start
        volumes:
            - ./server:/app
            - /app/node_modules
        networks:
            - geek-regime
        expose:
            - 8000
        depends_on:
            - postgres
            - redis
        environment:
            - PG_DATABASE
            - PG_DATABASE_DEV
            - PG_HOST
            - PG_PASSWORD
            - PG_PORT
            - PG_USER
            - HOST
            - PORT
            - REDIS_HOST
            - REDIS_PORT
            - SESSION_SECRET
            - URL
    postgres:
        image: postgres:12.1-alpine
        networks:
            - geek-regime
        expose:
            - 5432
        environment:
            POSTGRES_USER: admin
            POSTGRES_DB: geek-regime
    redis:
        image: redis:5.0.7-alpine
        networks:
            - geek-regime
        expose:
            - 6379
        command: ["redis-server", "--appendonly", "yes"]
networks:
    geek-regime:
        driver: bridge
