version: "3.3"
services:
    client:
        build: ./client
        command: npm start
        volumes:
            - ./client:/app
            - /app/node_modules
        networks:
            - geek-regime
        ports:
            - 10000:3000
        depends_on:
            - server
            - postgres
            - redis
    server:
        build: ./server
        command: npm start
        volumes:
            - ./server:/app
            - /app/node_modules
        networks:
            - geek-regime
        expose:
            - 8000
        depends_on:
            - postgres
            - redis
        environment:
            - HOST
            - PG_URL
            - PG_URL_DEV
            - PORT
            - REDIS_HOST
            - REDIS_PORT
            - SESSION_SECRET
            - URL
    postgres:
        image: postgres:12.1-alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - geek-regime
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
    redis:
        image: redis:5.0.7-alpine
        networks:
            - geek-regime
        expose:
            - 6379
        command: ["redis-server", "--appendonly", "yes"]
networks:
    geek-regime:
        driver: bridge
volumes:
    postgres-data:
        driver: local
