version: "3.3"
services:
    client:
        networks:
            - geek-regime
        depends_on:
            - server
            - postgres
            - redis
    server:
        networks:
            - geek-regime
        depends_on:
            - postgres
            - redis
        ports:
            - ${PORT}:${PORT}
        environment:
            - HOST
            - PORT
            - POSTGRES_URL
            - POSTGRES_URL_TEST
            - PROJECT_NAME_FULL
            - PROJECT_NAME_SHORT
            - REDIS_HOST
            - REDIS_PORT
            - SENDER_EMAIL
            - SENDGRID_API_KEY
            - SESSION_NAME
            - SESSION_SECRET
            - URL
    postgres:
        image: postgres:12.1-alpine
        restart: always
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - postgres-data:${PGDATA}
        networks:
            - geek-regime
        ports:
            - 5433:${POSTGRES_PORT}
        environment:
            - PGDATA=${PGDATA}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_DB_TEST=${POSTGRES_DB_TEST}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
    redis:
        image: redis:5.0.7-alpine
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redis-data:/data
        networks:
            - geek-regime
networks:
    geek-regime:
        driver: bridge
volumes:
    postgres-data:
        driver: local
    redis-data:
        driver: local
